### ISSUE TITLE
Constantly Getting "(DUPLICATE_REQUEST_ID)PayPal-Request-Id header was already used." for PayPal Pro requests.

### ISSUE THREAD

**Issue by tjhackzy** [paypal/PayPal-NET-SDK#348] opened 2018-04-09 13:46 UTC
### General information

* SDK/Library version: 1.9.1
* Environment: Sandbox
* `PayPal-Debug-ID` values: 78e612c538586 , 8d1c4a60b3e6e
* Language, language version, and OS: EN-US, Win10

### Issue description
We're constantly getting "{"name":"DUPLICATE_REQUEST_ID","message":"PayPal-Request-Id header was already used.","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"78e612c538586"} from PayPal Pro Response. AFAIK, I am providing all the details properly.

Here's a sample request : {"intent":"sale","payer":{"payment_method":"credit_card","funding_instruments":[{"credit_card":{"number":"4877274905927862","type":"visa","expire_month":3,"expire_year":2021,"cvv2":"123","first_name":"asdf","last_name":" asdf","billing_address":{"phone":"9898989898","line1":"maurayansh elanza ","line2":"","city":"Ahmedabad","country_code":"CU","postal_code":"380015","state":"Gujarat"}}}],"payer_info":{"email":"Jay_c_moar_15@gmail.com"}},"transactions":[{"amount":{"currency":"USD","total":"54.00","details":{"subtotal":"54.00","shipping":"0","tax":"0"}},"description":"SSL Certificates purchase from comodosslstore.com","invoice_number":"COR82910467M99101","item_list":{"items":[{"sku":"COR82910467M99101","name":"SSL Certificates","description":"SSL Certificates purchase from comodosslstore.com","quantity":"1","price":"54.00","currency":"USD","tax":"0"}]}}]}

**Comment by tjhackzy** [comment] 2018-04-09 13:49
I have even used  apiContext.ResetRequestId(); to reset the header request ID but no luck.

**Comment by xiaoleih41** [comment] 2018-04-09 15:53
This issue can be caused by many factors. If you google this error, you will find out quite a few issues raised in github that have caused this issue. You may get more insight on possible cause for your case. However, the credit card payment method has been deprecated. No new application will be approved for live production. Please consider to integrate braintree SDK instead for detail, please read [README.MD](https://github.com/paypal/PayPal-NET-SDK) of this repository.

**Comment by xiaoleih41** [comment] 2018-04-13 16:28
Close this issue as the potential solution has been given and an alternative product has been recommended.

**Closed by xiaoleih41** 2018-04-13 16:28 UTC

**Comment by lrice** [comment] 2018-04-18 19:01
I was told by support that credit card processing via the REST API is not deprecated, it has just been removed from new accounts available services. Our existing account still lists "Direct credit cards" as available for both sandbox and live. Live processing still works and it was confirmed for me that it wasn't going to be disabled any time soon, they are just pushing BrainTree and other payment methods for business purposes. I've put in a request to have direct credit cards processing enabled on another account. 

I am having these same issues with the sandbox. It could have to do with the warning on this page (similar issue): https://www.paypal-community.com/t5/Sandbox-Environment/PayPal-REST-payments-API/td-p/1333777

Since this issue isn't affecting our live systems, and it was confirmed for me that live processing was not going away we are going to continue using the REST integration we already have. You should confirm it for yourself, but that was what I heard from paypal support.

**Comment by xiaoleih41** [comment] 2018-04-19 16:41
If you can get the live credentials then it will be ok for you to use however it is showing deprecated status which means no more feature updates available for this product.

**Comment by lrice** [comment] 2018-04-19 18:52
That is fine, but the impression that it gave me was that it was no longer available (which was compounded by other things I read on other forums). For a lot of projects it is an attractive solution due to the ease of integration. Pushing people to other products for business reasons could be misleading when all you need is simple credit card processing.
