### ISSUE TITLE
Plan.List returns null merchant_preferences and payment_definitions.

### ISSUE THREAD

**Issue by projectzerotohero** [paypal/PayPal-NET-SDK#87] opened 2015-04-09 08:21 UTC
Hi there!

I have this ActionMethod on my controller to get the list of Billing plans I created.

````csharp
public ActionResult GetBillingPlans()
{
     PlanList newPlanList = Plan.List(apiContext, "0", "CREATED", "10", "yes");
     PlanList activePlanList = Plan.List(apiContext, "0", "ACTIVE", "10", "yes");
           
     var plans = new PayPalBillingPlanListViewModel()
     {
         NewBillingPlans = newPlanList,
         ActiveBillingPlans = activePlanList
     };

     return View(plans);
}
````

However, when the `Plan.List` method is called it returns the list of plans but with null `merchant_preferences` and `payment_definitions`.

May I know the reason behind this? 

Thanks!

**Comment by jziaja** [comment] 2015-04-09 13:12
Hi @projectzerotohero , I'm seeing the same behavior which does seem very odd.  Doing a `Get` on an individual plan returns all the details, but for some reason the `List` call doesn't.  I'm reaching out to the API team with this question to find the reason behind it.  Ideally, `List` should return the full details of each plan and not a subset.

**Comment by projectzerotohero** [comment] 2015-04-11 02:31
@jziaja Yes, that seems very odd. 
I'll just wait for an update. Thanks.

**Comment by jziaja** [comment] 2015-04-13 13:42
@projectzerotohero , sorry for the delay.  The API team responded saying this is expected behavior.  Their explanation is that the `Plan.List` method provides a list of resources that contain just the basic plan information.  I informed them that along with this being confusing and undocumented, this results in a fair number of uses cases requiring an extra `Get` call for each plan because of the missing information.  I am currently working with our documentation team to see if this can be better explained in the PayPal Developer docs.

**Comment by projectzerotohero** [comment] 2015-04-18 00:21
@jziaja , I see. I respect the team's decision but wouldn't it be better if the Plan.List method provides a list of resources that contains all the needed information?
Just saying.

**Comment by jziaja** [comment] 2015-04-22 15:00
@projectzerotohero - Definitely agree with you on that, and the API team is taking this feedback into future consideration.  I'll close this issue once the PayPal Developer documentation has been updated to clarify this behavior.

**Comment by projectzerotohero** [comment] 2015-04-23 01:22
@jziaja  Ok. Thanks. I'm glad to contribute to the API. :)

**Comment by jziaja** [comment] 2015-05-01 17:49
[Developer documentation](https://github.paypal.com/pages/alette/paypal-developer-docs/api/#list-plans) has been updated to include this note.  Thanks again for bringing this to our attention!

**Closed by jziaja** 2015-05-01 17:49 UTC
Labels: api-subscription, documentation

**Comment by kstubs** [comment] 2016-03-22 17:34
Can you tell me where this developer documentation is please?  Also, is there a work around to getting a list of recurring payment plans?  There is a bit of chicken/egg issue here in that I need to be able to cancel a plan so I need the plan ID, but I'm not sure how to get that plan ID without searching the plans.  This question is posted [here](http://stackoverflow.com/questions/36160144/paypal-recurring-plan-list-is-null) in stack as well.

**Comment by pp-randy** [comment] 2016-03-23 14:30
@kstubs here is the developer site documentation https://developer.paypal.com/docs/rest/api/payments.billing-plans/#list

The above provides a cURL example. Are you able to test in cURL?  If so, please see if this provides you results after adding an access token.
`curl -v -X GET https://api.sandbox.paypal.com/v1/payments/billing-plans?page_size=10&status=CREATED&page=1&total_required=yes \
-H 'Content-Type:application/json' \
-H 'Authorization: Bearer <Access-Token>' \
-d '{}'`

If you received no results for the CREATED curl, try this ACTIVE curl. 
`curl -v -X GET https://api.sandbox.paypal.com/v1/payments/billing-plans?page_size=10&status=ACTIVE&page=1&total_required=yes \
-H 'Content-Type:application/json' \
-H 'Authorization: Bearer <Access-Token>' \
-d '{}'`

I do not see status in the SDK https://github.com/paypal/PayPal-NET-SDK/blob/master/Source/SDK/Api/PlanList.cs, if your Plans are active status would need to be passed in to see them, **I will follow up more internally on the status parameter**.  If you show results for ACTIVE and not CREATED then this could be a possible reason.

**Comment by kstubs** [comment] 2016-03-24 09:24
Randy, I've moved onto another api, the PayPal merchant, https://github.com/paypal/merchant-sdk-dotnet I moved on because according to PayPal support I would not be able to cancel a recurring payment made from PayPal's Express Check Out with the Rest API.  But of course now I'm facing a new challenge, I'm facing new challenges now with TLSv1.2 policies going into place at PayPal.  I have the code that I need working but getting this intermittent error:  The request was aborted: Could not create SSL/TLS secure channel.
I've heard lots of mentions of curl but have never used it.  I'm primarily a Windows guy.
Thanks for this post!  I may be coming back to it soon.

**Comment by pp-randy** [comment] 2016-03-24 13:13
@kstubs For that SDK make sure you have an updated https://github.com/paypal/sdk-core-dotnet. Create an issue in repo https://github.com/paypal/merchant-sdk-dotnet if you have issues moving forward, we are here to help.

**Comment by juwlee** [comment] 2016-03-24 13:47
@kstubs To add to what @pp-randy said, please see [.NET SDK TLS docs](https://github.com/paypal/TLS-update#paypal-net-sdk-support).

**Comment by pp-randy** [comment] 2016-03-24 14:15
To follow up further with the context of the sample here: https://github.com/paypal/PayPal-NET-SDK/blob/develop/Samples/Source/BillingPlanGetList.aspx.cs#L41

To show ACTIVE plans you would use a parameter list like the following:
`var planList = Plan.List(apiContext, "0", "ACTIVE", "10", "yes");`

https://github.com/paypal/PayPal-NET-SDK/blob/develop/Source/SDK/Api/Plan.cs#L163
