### ISSUE TITLE
New Version

### ISSUE THREAD

**Issue by okankocyigit** [paypal/PayPal-NET-SDK#285] opened 2017-08-25 10:16 UTC
Will you release a new version to nuget, there are some critical bugs which has been fixed after v1.8.0?

**Comment by tomkerkhove** [comment] 2017-08-25 10:21
Duplicate of #279 but they are going to ship a new one soon.
Can you confirm this @pp-randy?

**Comment by pp-randy** [comment] 2017-08-25 14:31
I will follow up on getting this updated.  I will use https://github.com/paypal/PayPal-NET-SDK/issues/279 for tracking.

**Closed** 2017-08-25 14:32 UTC
