### ISSUE TITLE
Sample code is not running on dotnet 4.0 with visual studio 2010 on windows server 2008

### ISSUE THREAD

**Issue by billsliu** [paypal/PayPal-NET-SDK#220] opened 2016-11-22 20:31 UTC
I am running sample code on dotnet 4.0 with visual studio 2010 on windows server 2008, it always generate exception "retried 1 times.... Exception in PayPal.HttpConnection.Execute()". Even I add following code to
global.asax.cs file

        protected void Application_Start(object sender, EventArgs e)
        {
            // SecurityProtocolType.Tls12
            ServicePointManager.SecurityProtocol = (SecurityProtocolType)3072; 
        }
I changed run mode from "sandbox" to "security-test-sandbox" in web.config file

The problem is still there.

But I run the sample code on dotnet 4.0 with visual studio 2010 on windows 10 computer, it works fine. 

This windows server 2008 is running fine using Stripe.net to communicate with Stripe with TLS 1.2 on the same environment.
https://support.stripe.com/questions/how-do-i-upgrade-my-stripe-integration-from-tls-1-0-to-tls-1-2#dotnet

The problem is related to PayPal NET SDK handling HTTPS connection with TLS 1.2 on windows server 2008.

**Comment by pp-randy** [comment] 2016-11-29 22:16
Hi Billsliu,

Can you review https://github.com/paypal/tls-update#net?  

Is your Stripe application targeting a .Net framework of 4.5 or higher? 

Unrelated to the SDK, I had a recent experience of my own updating to higher .Net framework and Visual Studio 2010 wasn't showing any framework options higher than 4.0 in the solution properties, so unfortunately I had to hack the web.config values for httpRuntime targetFramework.  Then I used wireshark and confirmed TLS 1.2 was being used.

**Comment by billsliu** [comment] 2016-12-01 01:41
If I build the application using visual studio 2010 with framework option 4.0, it is fine if the computer has dot net framework 4.5 or above installed. I can publish this application to windows 7, 8, 10 or windows server 2008 r2, 2012 or 2016, they all run fine and communication using TLS 1.2.  If I run the application on Vista or windows server 2008, the communication using TLS 1.0. I found out the problem is not PayPal Net Sdk, windows vista and windows 2008 server do not support TLS 1.2, dot net framework's support of TLS 1.2 depending on operating system. The problem is Microsoft want us to abondon old windows machine and buy their new product, greedy.

**Comment by pp-randy** [comment] 2016-12-01 17:54
I was able to get .Net Framework 4.6.2 installed in Server 2008 to use TLS 1.2, but I had to modify the web.config in my application's IIS directory.  It still uses 4.6 even if IIS7 does not show that it is above 4.0 in the Application Pool. 
` <system.web>
     <httpRuntime enableVersionHeader="false" targetFramework="4.6.2"/>`

You could always test this out and see how it goes.  Keep in mind the targetFramework needs to match the version you installed.

**Comment by billsliu** [comment] 2016-12-02 04:21
.Net Framework 4.6.2 is not supported in Windows Server 2008, see the link [https://www.microsoft.com/en-us/download/details.aspx?id=53345](url) I can only install .Net 4.5.2 on Windows Server 2008. I made change to web.config file <httpRuntime enableVersionHeader="false" targetFramework="4.5.2"/>. It is not working either.

Do you really test it on Windows server 2008? I guess you test it on Windows server 2008 R2. 
Windows server 2008 use the same core as Vista, 
Windows server 2008 R2 use the same core as Windows 7

TLS 1.2 supporting operating system are Windows server 2008 R2 above or Windows 7 above.
See the link [https://support.microsoft.com/en-us/kb/3140245](url)

**Comment by pp-randy** [comment] 2016-12-02 10:21
It was R2

**Comment by pp-randy** [comment] 2016-12-05 15:28
Closing the issue since it is related to the server environment and not the SDK.  I hope you are able to get things figured out.  Please let me know if there is anything I can help you with otherwise.

**Closed by pp-randy** 2016-12-05 15:28 UTC
Labels: question
