### ISSUE TITLE
Cost serialization does not validate when used as Invoice discount amount

### ISSUE THREAD

**Issue by dacoapconsulting** [paypal/PayPal-NET-SDK#338] opened 2018-02-05 14:53 UTC
I'm creating an invoice and i've found a problem when i try to set only the discount amount of an item:
```
new InvoiceItem()
                    {
                        name = "Articolo Prova 1 ",
                        quantity = 1,
                        unit_price = new Currency()
                        {
                            currency = "EUR",
                            value = "13.50"
                        },
                        tax = new Tax() {
                            
                            name = idromec.template_data.items[0].tax.name,
                            percent = idromec.template_data.items[0].tax.percent

                            
                        },
                        discount = new Cost() {
                            amount = new Currency()
                            {
                                currency = "EUR",
                                value = "2.70"
                            }

                        }
                    }
```
As you can see in the resulting Invoice, converted in JSON, down below, the amount has setted right but a percent value 0.0 appear:

```
{"name":"Articolo Prova 1 ","quantity":1.0,"unit_price":{"currency":"EUR","value":"13.50"},
"tax":{"name":"IVA","percent":22.0},"discount":{"percent":0.0,"amount":{"currency":"EUR","value":"2.70"}}},
```
That percent value doesn't let me validate the invoice, and i'm sure of that because i've tried to remove it  manually from the json and it has worked (here's how):

```

public class MyInvoice : PayPal.Api.Invoice
    {
        public MyInvoice()
        {
        }

        public override string ConvertToJson()
        {
            string json = base.ConvertToJson();
            return json.Replace("\"percent\":0.0,", "");
        }
    }
```

The problem is that it's not possible to avoid the serialization of the percent property, please try to solve it.

NB. the invoice.discount summary tell that it can be set as a percent OR an amount and right now it's not possible. 

PLEASE RESOLVE IT.

P.s. i've resolved with something like this instead of Cost():

```
public class DiscountAmount : PayPal.Api.Cost
    {
        public DiscountAmount() {
        }
        
        [JsonProperty(DefaultValueHandling=DefaultValueHandling.Ignore, PropertyName="percent")]
        public new float percent;
    }
```

**Comment by xiaoleih41** [comment] 2018-02-05 16:13
This is caused by the not null-able **float** type of  the **percent** parameter. This issue has been fixed in [the SDK v2 beta version](https://github.com/paypal/PayPal-NET-SDK/blob/2.0-beta/Source/v1/Invoices/Cost.cs#L34), please consider to switch to the [V2 version of this SDK](https://github.com/paypal/PayPal-NET-SDK/tree/2.0-beta).

**Comment by sucithrashanu** [comment] 2019-12-20 06:48
@dacoapconsulting 

Currently we do not have any stipulated timeline for the v2.0.0 release, but it may be available in near future.

Please Check [PayPal Community](https://www.paypal-community.com) and  [MTS](https://paypal.com/mts)

Thanks!

**Closed by sucithrashanu** 2019-12-20 06:48 UTC
Labels: 2.0-beta, sdk-bug
