### ISSUE TITLE
HttpException occurred when trying to use basic call.

### ISSUE THREAD

**Issue by Vincenttbk** [paypal/PayPal-NET-SDK#95] opened 2015-05-03 13:55 UTC
Hi, 

Im really new to .net and Im trying to make use of the SDK to help me make some call to get my transaction ID.

I've followed the "tutorial" but when I was trying to make a call, I got a HttpException.

"An exception of type 'PayPal.HttpException' occurred in PayPal.dll but was not handled in user code
Additional information: The remote server returned an error: (404) Not Found."

The code I had is of below,

````csharp
var config = ConfigManager.Instance.GetProperties();
var accessToken = new OAuthTokenCredential(config).GetAccessToken();
var apiContext = new APIContext(accessToken);

// Initialize the apiContext's configuration with the default configuration for this application.
apiContext.Config = ConfigManager.Instance.GetProperties();

// Define any custom configuration settings for calls that will use this object.
apiContext.Config["connectionTimeout"] = "1000";
// Define any HTTP headers to be used in HTTP requests made with this APIContext object
if (apiContext.HTTPHeaders == null)
{
    apiContext.HTTPHeaders = new Dictionary<string, string>();
}
apiContext.HTTPHeaders["Content-Type"] = "application/json";

var payment = Payment.Get(apiContext, "PAY-0XL713371A312273YKE2GCNI");
````

Hope the information are enough and someone can help me with the code above.

Thank you :)

**Comment by jziaja** [comment] 2015-05-03 14:52
Hi @Vincenttbk, the 404 error indicates that the requested resource wasn't found using your supplied credentials.  

To help figure out what's going, I have a few questions:
* Did you setup your web.config file with the appropriate PayPal settings?  
  * _Refer to the [Configure the SDK](https://github.com/paypal/PayPal-NET-SDK/wiki/Configuration) wiki page for an example of how to properly setup the file with your application credentials._
* Is this on sandbox or live, and are your `clientId` and `clientSecret` set correctly in your web.config?
* What tutorial were you trying to follow?
* What version of the SDK are you using?

Thanks!

**Comment by Vincenttbk** [comment] 2015-05-03 15:19
Hi, 

I think so, I've copied the configuration, the configuration is as below, I've taken out my secret and ID.
<configSections>
    <section name="paypal" type="PayPal.SDKConfigHandler, PayPal" />
  </configSections>

  
  <paypal>
    <settings>
      <add name="mode" value="sandbox"/>
      <add name="clientId" value="MyOwnID"/>
      <add name="clientSecret" value="MyOwnSecret"/>
    </settings>
  </paypal>

I am currently using 1.4.2 of the SDK.

The tutorial is getting started page.

Thanks :)

**Comment by jziaja** [comment] 2015-05-03 16:27
Is the payment you're trying to lookup from a live or sandbox transaction?

**Comment by Vincenttbk** [comment] 2015-05-04 01:05
hihi!
Oh! Silly me, is it because I can't find a payment ID? It is not the 404 because there is a problem with an endpoint?

Thanks! Will try it out :)

**Comment by Vincenttbk** [comment] 2015-05-04 03:52
Hi, 

The previous way works! Thanks!
Just another short question, Im trying to do a refund however i got a bad request.

My code are as follow:

                var payment = Payment.Get(apiContext, payResource);
                //To get out the Transaction ID

                var saleID = payment.transactions.Select(x => x.related_resources).Select(resource => resource.First().sale.id).First();

                //Set the booking info
                Sale sale = Sale.Get(apiContext, saleID);

                Amount amount = new Amount();
                amount.total = "5.00";
                amount.currency = "SGD";

                Refund refund = new Refund();
                refund.amount = amount;

                Refund itemRef = Sale.Refund(apiContext, saleID, refund);
                result = JsonConvert.SerializeObject(itemRef);

**Comment by jziaja** [comment] 2015-05-04 13:01
The exception thrown for a 400 error should include a `Response` property that explains what caused the error.  Would you mind sharing what response you received?

**Comment by Vincenttbk** [comment] 2015-05-04 13:54
Hi,

Is this what you are looking for? 

{"name":"TRANSACTION_REFUSED","message":"The request was refused.{0}","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#TRANSACTION_REFUSED","debug_id":"da3b50630b270"}

Thanks :)

**Comment by jziaja** [comment] 2015-05-04 14:06
Thanks for the info, @Vincenttbk.  We're looking into it, as a transaction refusal could be for a number of reasons.  I'll followup here once I have more information.

**Comment by Vincenttbk** [comment] 2015-05-04 15:04
Thank you @jziaja, Hope to hear from you soon! :)

**Comment by jziaja** [comment] 2015-05-04 15:55
@Vincenttbk we're unable to lookup the details for that transaction using the `debug_id` included with your previous response.  

To help us out, would mind providing the following information:
* the ID of the `Sale` resource you're trying to refund
* date/timestamp (including timezone) of when you received the error

Thanks!

**Comment by Vincenttbk** [comment] 2015-05-04 23:34
Hi @jziaja, Im unable to find a timestamp, but I executed the logic around 0730am(GMT+8) time and the transaction ID is 3AW477265S101141M.

Hope that helps? :)

**Comment by jziaja** [comment] 2015-05-05 19:21
@Vincenttbk , thanks for sharing that information.  We were able to find out that the refund is failing because the original payment has a status of 'unclaimed' and is in a pending state until you accept or deny the payment.  The cause for this is the payment was sent in a currency different than the currency held by your facilitator account, and you have your account set up to manually accept/deny when this happens.

Before the refund can be issued, it will first need to be accepted by your facilitator account (you can do this by logging into your facilitator account and accepting the pending payment).  Can you try that out and let me know if it resolves your issue of being able to issue the refund?

**Comment by Vincenttbk** [comment] 2015-05-06 02:06
Oh, I think because it is a sandbox account, that is why payments are not accepted automatically?
Thanks! I will try it out!

**Comment by jziaja** [comment] 2015-05-22 17:58
@Vincenttbk were you able to resolve this issue by accepting the pending payment in your facilitator account?

**Comment by jziaja** [comment] 2015-05-28 16:16
Closing this issue. Please reopen it or contact [PayPal Merchant Technical Support](ppmts.custhelp.com) if you continue to experience the issue.  Thanks!

**Closed by jziaja** 2015-05-28 16:16 UTC
Labels: question

**Comment by Vincenttbk** [comment] 2015-06-16 04:58
Hi, Sorry, I think its a configuration issue, I tried using apiContext in my .net logic to get the mode which is live, but it is grabbing from my web.config.
