### ISSUE TITLE
Creating payment: "INTERNAL_SERVICE_ERROR"

### ISSUE THREAD

**Issue by DanielHaddon** [paypal/PayPal-NET-SDK#120] opened 2015-10-01 10:54 UTC
Hey guys Im using the .NET nuget package for this SDK and Im constantly getting 500 errors. Ive tried everything I can think of and searched through every issue I can but to no avail. Please help me.

Basically this issue is occuring when I call:

paypalPayment = payment.Create(Paypal.Configuration.GetAPIContext());

Sometimes it works but half the time it doesnt, which is really frustrating.

My debug ID is: 72c15f3d6c0d3 

Error details:
The remote server returned an error: (500) Internal Server Error.

Stack trace:
   at PayPal.Api.HttpConnection.Execute(String payLoad, HttpWebRequest httpRequest)
   at PayPal.Api.PayPalResource.ConfigureAndExecute[T](APIContext apiContext, HttpMethod httpMethod, String resource, String payload, String endpoint)
   at PayPal.Api.Payment.Create(APIContext apiContext, Payment payment)
   at PayPal.Api.Payment.Create(APIContext apiContext)
   at Unity.Controllers.PurchaseController.InitialisePaypalPayment(JSONPaypalPayment jsonPaypalPayment)

Please help!

**Comment by DanielHaddon** [comment] 2015-10-01 12:30
I figured it out. Well.. I just re-downloaded the sample and worked through and checked that every variable was exactly as it should be. A few things like the sku for my items not being set is what I think was the problem.

**Comment by jziaja** [comment] 2015-10-01 12:42
Interesting, are you able to reproduce the 500 error with the invalid sku?  If so, could you share what the `Payment` object looks like prior to making the `Create()` call?  Thanks!

**Comment by ppmtscory** [comment] 2015-10-09 19:22
Closing for now.  If you are able to reproduce again, please let us know so that we can correct the 500 error.

**Closed by ppmtscory** 2015-10-09 19:22 UTC
Labels: api-payments
