### ISSUE TITLE
Could not find member 'soft_descriptor' on object of type 'Sale'.

### ISSUE THREAD

**Issue by michelmob** [paypal/PayPal-NET-SDK#236] opened 2017-02-17 14:09 UTC
I'm getting this "intermitent "error during the execute method:

Error while deserializing JSON: Could not find member 'soft_descriptor' on object of type 'Sale'. Path 'transactions[0].related_resources[0].sale.soft_descriptor'

Can you guys help me?

**Comment by pp-randy** [comment] 2017-03-01 18:07
@michelmob how are you using this field? 

Its not very clear in the REST API documentation, the soft descriptor is used in the customer statements so it is mainly used as part of the request for a transaction. 

It is described as PAYMENTREQUEST_n_SOFTDESCRIPTOR in our merchant API here:  
https://developer.paypal.com/docs/classic/api/merchant/DoExpressCheckoutPayment_API_Operation_NVP/

**Comment by pp-randy** [comment] 2017-03-07 15:31
Closing this issue please let me know if you need further assistance.

**Comment by evgrud** [comment] 2017-04-18 09:15
I will answer for @michelmob because I'm having the same issue: We aren't using the 'soft_descriptor' field at all.  This error is being logged from deep within the SDK and it seems to be handled because there is no exception being thrown outside. However, having this error being logged for each transaction is bothersome.

**Comment by pp-randy** [comment] 2017-04-20 16:05
@evgrud this only occurs randomly during some payment execute calls?  Does it happen on sandbox or only on live?

**Comment by s4lvo** [comment] 2017-04-21 06:46
@pp-randy I have the same problem, and It happen on live enviroment for each transaction

**Comment by evgrud** [comment] 2017-04-21 09:58
For me, I think it happens 100% of the time, also on sandbox. If you can't reproduce, I can provide more details like trying to get the raw request/response (from my sandbox).

**Comment by pp-randy** [comment] 2017-05-03 13:46
@evgrud requests and responses would help.  I will review the logging further as well.  If anyone has a fix feel free to submit a pull request.

**Comment by pp-randy** [comment] 2017-05-03 14:14
So the problem is most likely soft_descriptor not being spelled out here https://github.com/paypal/PayPal-NET-SDK/blob/develop/Source/SDK/Api/Sale.cs#L20

**Comment by pp-randy** [comment] 2017-05-03 14:45
@evgrud the response strings would be super at this point if you have time to provide them since I am not getting a soft_descriptor returned in my tests.

**Comment by pp-randy** [comment] 2017-05-03 18:15
I have a pull request that should help with the error being generated here https://github.com/paypal/PayPal-NET-SDK/pull/257

**Comment by pp-randy** [comment] 2017-05-08 20:46
Closing the issue as the above pull request should resolve the issue for the SDK. 

I anyone does get a response with soft-descriptor and is willing to share it, I would be grateful and will follow up on the API side of things.

**Closed by pp-randy** 2017-05-08 20:46 UTC
Labels: question, sdk-bug

**Comment by evgrud** [comment] 2017-05-26 12:41
For the record, I stopped getting this error even without upgrading the SDK, I guess the server stopped sending the extra field.
