### ISSUE TITLE
 Payment.List returns all transactions independent of payeeId parameter

### ISSUE THREAD

**Issue by polyakova** [paypal/PayPal-NET-SDK#88] opened 2015-04-09 13:43 UTC
I want to get all transactions of concrete user and do this request:
`var paymentList = Payment.List(apiContext, count: 10, payeeId: "MXGL8TNAPEY4J")`

It takes about 20 seconds (i believe it's too long for production environment) and returns me all the transactions for my merchant account.

In method documentation is written that Payee can be passed to filter transactions list:
 Payee identifier (merchant id) assigned by PayPal to filter the search results

**Comment by jziaja** [comment] 2015-04-09 14:31
Thanks for reporting this, @polyakova.  I'm seeing the same behavior when I try to search the payment history for any `payeeId'.  I'm reaching out to the API team to get clarification on why this is happening and will get back to you once I hear back from them.

Also, I agree that 20 seconds is way too long for a search operation to complete in a production environment.  When you make `Payment.List` call, are you able to capture the details of the received response and find a `correlation-id` in the response header?  The API team can use this identifier as a starting point for figuring out why the search operation is taking so long.

**Comment by polyakova** [comment] 2015-04-09 14:48
@jziaja I didn't find correlation-id in headers. I found only Paypal-Debug-Id.

**Comment by jziaja** [comment] 2015-04-09 14:51
Ah sorry, that's the ID I meant. :)

**Comment by polyakova** [comment] 2015-04-09 14:52
Paypal-Debug-Id: "b3d1987c8cc5d"

**Comment by jziaja** [comment] 2015-04-10 12:50
@polyakova , I've opened two tickets with the API team regarding these issues:

> **PPTIPS-3370**: Search on payment history with payee_id as a parameter is not working

> **PPTIPS-3372**: Search on payment history takes over 20 seconds on live

The API team doesn't have an ETA on when these issues will be resolved, but they do think they are related.  They are currently in the process of identifying the root cause.  I'll keep you posted here as soon as I have more information to share.

**Comment by jziaja** [comment] 2015-04-24 19:09
@polyakova , would you mind trying the search again using the `payee_id`?  The search issue should now be resolved on the live service.

The API team did respond that they are aware of the fact that some searches are taking a long time to complete.  Their suggestion is to reduce the search window by including `start_time` and `end_time` in the search parameters.  Would you also mind trying that out and see if you still experience a long delay in getting the search results?

Thanks!

**Comment by jziaja** [comment] 2015-05-06 20:46
Closing this issue.  Please reopen this issue if you still encounter the issue.  Thanks!

**Closed by jziaja** 2015-05-06 20:46 UTC
Labels: api-bug, api-payments
