### ISSUE TITLE
HTTP 500: INTERNAL_SERVICE_ERROR on credit_card with item_list

### ISSUE THREAD

**Issue by EdSF** [paypal/PayPal-NET-SDK#61] opened 2015-01-02 02:52 UTC
Perhaps related to [this closed issue?](https://github.com/paypal/PayPal-NET-SDK/issues/30)

This error is (so far for me) returned 100% of the time if I include `item_list` in the `transaction`. Removing the`item_list` will complete successfully (so far 100% of the time).

Sounds simple enough (then don't include `item_list`), **but** the error is _"cosmetic"_. The transaction in fact **succeeds** as shown:

![creditcarditemdetail](https://cloud.githubusercontent.com/assets/636166/5593947/c0c94c62-91e5-11e4-8478-b0448d7eee29.PNG)

I can even "Print a packing slip"  - re: `shipping_address` is included in `item_list`

![packslip](https://cloud.githubusercontent.com/assets/636166/5593969/9f5eadf0-91e6-11e4-9457-9cbea2c01534.PNG)

Thanks for any input and happy new year!

**Comment by jziaja** [comment] 2015-01-02 15:22
Thanks for reporting this @EdSF.  Does the 500 error response contain any other information (like `debug_id`)?

**Comment by EdSF** [comment] 2015-01-02 16:38
Hi Jason,

Oops, forgot to add that part. Yes:

    {
	  "name": "INTERNAL_SERVICE_ERROR",
	  "message": "An internal service error has occurred",
	  "information_link": "https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_SERVICE_ERROR",
	  "debug_id": "bed2efa986965"
     }

If it helps at all, just repro a minute or so ago, the ID for this specific repro (obtained from the Sandbox site):

    Payment Platform API  (Swiped) (Unique Transaction ID #7968461536242031J)

Thanks!

**Comment by jziaja** [comment] 2015-01-02 17:02
Thanks @EdSF, it looks like there's a lot of internal exceptions occurring in the backend service. I tried reproducing this, but I didn't encounter any problems.  To help in debugging this issue (and to provide the API team with more detailed information for how to reproduce the issue), I'll need to know the following information:
* What SDK calls are you making?
* What does the request body being sent look like?

Thanks!

**Comment by EdSF** [comment] 2015-01-02 18:13
Hi Jason,

I'm using the .Net SDK (latest, via Nuget).
 1. create the ApiContext
 2. build the necessary objects (`Payer`, `Transaction`, etc)
 3. build `Payment` and then call `Create`

Am using the SDK so for the raw data (payload), I called `ConvertToJson()` on `Payment`:

    {
	 "intent": "sale",
	 "payer": {
		 "payment_method": "credit_card",
		 "funding_instruments": [{
			 "credit_card": {
				"number": "4417119669820331",
				"type": "visa",
				"expire_month": 11,
				"expire_year": 2018,
				"cvv2": "874",
				"first_name": "Card",
				"last_name": "Holder",
				"billing_address": {
					"line1": "123 Bill City",
					"city": "Bill City",
					"country_code": "US",
					"postal_code": "94111",
					"state": "CA"
				}
			}
		}],
		 "payer_info": {
			 "email": "canuser1@noemail.com"
		}
	},
	 "transactions": [{
		 "amount": {
			 "currency": "USD",
			 "total": "23.93",
			 "details": {
				 "subtotal": "19.94",
				 "shipping": "3.99",
				 "tax": "0"
			}
		},
		 "description": "Test Guest Checkout",
		 "invoice_number": "1420219038",
		 "item_list": {
			 "items": [{
				"quantity": "1",
				"name": "item name 1",
				"description": "description 1",
				"price": "1.99",
				"currency": "USD",
				"sku": "sku 1"
			},
			{
				"quantity": "2",
				"name": "item name 2",
				"description": "description 2",
				"price": "2.99",
				"currency": "USD",
				"sku": "sku 2"
			},
			{
				"quantity": "3",
				"name": "item name 3",
				"description": "description 3",
				"price": "3.99",
				"currency": "USD",
				"sku": "sku 3"
			}],
			 "shipping_address": {
				"recipient_name": "The Recipient",
				"line1": "123 Ship City",
				"city": "Ship City",
				"country_code": "US",
				"postal_code": "30303",
				"state": "GA"
			}
		}
	 }]
    }
  
Even if I use `curl` (not SDK), I can reproduce the error (using above payload - I did notice the string vs int for `expire_month` and `expire_year` though wrapping them in the `curl` call with quotes didn't seem to change anything):

    > POST /v1/payments/payment HTTP/1.1
    > User-Agent: curl/7.33.0
    > Host: api.sandbox.paypal.com
    > Accept: */*
    > Content-Type: application/json
    > Authorization: Bearer [the token]
    > Content-Length: 1103
    > Expect: 100-continue
    >
    < HTTP/1.1 100 Continue
    < HTTP/1.1 500 Internal Server Error
    * Server Apache-Coyote/1.1 is not blacklisted
    < Server: Apache-Coyote/1.1
    < PROXY_SERVER_INFO: host=slcsbplatformapiserv3001.slc.paypal.com;threadId=1011
    < Paypal-Debug-Id: 9fd6995fcbad6
    < SERVER_INFO: paymentsplatformserv:v1.payments.payment&CalThreadId=368&TopLevelTxnStartTime=14aabbe6852&Host=slcsbpaymentsplatformserv3002.slc.paypal
    .com&pid=7916
    < Content-Language: *
    < Date: Fri, 02 Jan 2015 17:43:40 GMT
    < Connection: close
    < Content-Type: application/json
    < Content-Length: 212
    < Connection: close
    <
    {"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error has occurred","information_link":"https://developer.paypal.com/webapps/developer
    /docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"9fd6995fcbad6"}* Closing connection 0
    * SSLv3, TLS alert, Client hello (1):



The successful transaction ID in Sandbox site for above: 
`Payment Platform API  (Swiped) (Unique Transaction ID #0BN00538TB461692M)`

Thank so much!

**Comment by jziaja** [comment] 2015-01-02 22:46
Thanks for the detailed information, @EdSF!  Using that payment object, I was able to successfully reproduce the issue.

I was able to get it to work by **changing the credit card number** (I tried it with `4446283280247004`, and the payment was successfully created).  Can you try that out and see if it works for you?  You can also generate a new test credit card to use against sandbox by creating a new sandbox test account from your [PayPal Developer Dashboard](https://developer.paypal.com/webapps/developer/applications/accounts/create).

The sandbox services for processing credit cards are a bit finicky, especially with card numbers that get used a lot.  This is something our team escalated a couple months ago with regards to guidance we give in the API developer docs on what credit cards to use when testing with the REST services.  The services teams are actively working on a better solution to not only generate credit card numbers to be used on sandbox, but also provide better guidance on PayPal Developer with respect to what cards should be used to test with on sandbox.

(cc [PayPal-PHP-SDK Issue #112](https://github.com/paypal/PayPal-PHP-SDK/issues/112))

**Comment by EdSF** [comment] 2015-01-03 00:23
Arg - that worked :)

Successful response (edited for brevity):

    {
          "id": "PAY-72891622GP4592738KSTTCAQ",
          "intent": "sale",
          "payer": {
           "payment_method": "credit_card",
           "funding_instruments": [
      {
        "credit_card": {
          "number": "xxxxxxxxxxxx7004",
          "type": "visa",
          ....
             
          "transactions": [
                {
                 "related_resources": [
                   {
                    "sale": {
                               "id": "9C013313B2462134P"
                      ....

Its really weird for it to fail only on the `response` and only the existence of an `item_list` (but transactions are successful)...caused by a test card :) One would expect it to "fail all" (fail response == failed transaction).

Finicky indeed :) 

In any case, THANK YOU, for your time on this!

**Comment by EdSF** [comment] 2015-01-03 16:54
Additional **feedback** - re: Negative Testing (_somewhat_ related to above - regarding errors):

I've been able to do negative testing (e.g. induce AVS errors), based on the [classic API guidance](https://developer.paypal.com/webapps/developer/docs/classic/lifecycle/sb_error-conditions/), but it seems there is no detail that is returned - other than the "type" of Exception re: -  above is a `PayPalException.HttpException` while negative testing throws a `PaymentsException`. 

For example, I induced an _AVS no match_ using `123 AVS_N Street` and this is the response:

    {
	"name": "UNKNOWN_ERROR",
	"message": "An unknown error has occurred",
	"information_link": "https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR",
	"debug_id": "9ae873ebc8778"
    }

It's a workable situation (at the end of the day, a failed payment is what it is), just hope there are plans to make this more helpful to distinguish.

Thanks again for all your work!

**Comment by jziaja** [comment] 2015-01-04 16:39
Thanks for the feedback @EdSF!  I'll forward this to the services team informing them there's a case where an AVS failure isn't returning an appropriate error.

Closing this issue as the CVV failure is a known issue the services team is currently working on to address.  If you encounter any other issues, please don't hesitate to open a new issue here and let us know. Thanks!

**Closed by jziaja** 2015-01-04 16:39 UTC
Labels: api-bug
