### ISSUE TITLE
Create payment from saved card .NET SDK INTERNAL_SERVICE_ERROR 

### ISSUE THREAD

**Issue by engmarconi** [paypal/PayPal-NET-SDK#282] opened 2017-08-22 20:30 UTC
Hello
I got this issue when try to create payment from saved card.
{"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error occurred.","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"b0dba817ede3f"}

Please any suggestions? 

Regards
Marco

**Comment by pp-randy** [comment] 2017-08-23 15:04
Can you try a new card number and let me know if you still encounter an error? Skip to the bottom of this FAQ and let me know if the issue persists https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1413.  

This is most likely related to https://github.com/paypal/PayPal-REST-API-issues/issues/22.  However, let me know if this is not the case and your error persists.

**Comment by engmarconi** [comment] 2017-08-23 16:58
I used more new cards and I still throw exception
{"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error occurred.","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"f7f4f5d136e32"}

**Comment by pp-randy** [comment] 2017-08-23 17:09
Can you provide the API request JSON?  I am seeing zeros in the expiration date fields and also commas in your amounts and what to confirm if these are being sent by you.

**Comment by pp-randy** [comment] 2017-08-23 17:14
I was able to reproduce with a higher dollar amount.  Are you going to create transactions on live for these high amounts?

**Comment by engmarconi** [comment] 2017-08-23 17:16
No, it was just for test.







* Marco M.S. KaldasResearcher & Software EngineerFaculty of Engineering ,
Minia UniversityMob : +201207639589Viber : +201207639589WhatsApp :
+201207639589*

**Comment by engmarconi** [comment] 2017-08-23 17:19
I'm using .Net SDK and this is the payment object passed to create method:
{"intent":"sale","payer":{"payment_method":"credit_card","funding_instruments":[{"credit_card_token":{"credit_card_id":"CARD-04T89613TL338221VLGO3JDI","expire_month":0,"expire_year":0}}]},"transactions":[{"amount":{"currency":"USD","total":"83,500.00","details":{"subtotal":"82,500.00","shipping":"1,000.00","tax":"0.00"}},"description":"Order # 210817055041-40D2 - Total = 83500.0000","custom":"{\"OrderNumber\":\"210817055041-40D2\"}"}]}

**Comment by pp-randy** [comment] 2017-08-23 17:36
Can you lower the amount and see if it works? 

If so, I will follow up for some better error messaging if this is the cause.

**Comment by engmarconi** [comment] 2017-08-23 17:51
Thanks Randy , Yes it related to amount values. Please add better error messages for it.
Regards

**Comment by bluk** [comment] 2018-02-21 15:47
Closing as the issue was identified, and it isn't a SDK issue. For any other REST API issues, you can open an issue on the [REST-API-Issues](https://github.com/paypal/PayPal-REST-API-issues) repository.

**Closed by bluk** 2018-02-21 15:47 UTC
Labels: question
