### ISSUE TITLE
UNKNOWN_ERROR causes exception in PayPal-NET-SDK

### ISSUE THREAD

**Issue by antonio-bakula** [paypal/PayPal-NET-SDK#74] opened 2015-02-02 14:52 UTC
I got UNKNOWN_ERROR from paypal (submiting a payment without state code for Canada or US) and when SDK processed this error in PaymentsException there was an null exception when that code tries to read from response details becouse there was no details and Details property was null.

Here is the JSON response from PayPal that causes this exception:

{
  "name":"UNKNOWN_ERROR",
  "message":"An unknown error has occurred",
  "information_link":"https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR",
  "debug_id":"2f14aa9749854"
}

And here is the screenshot from code:
![pp](https://cloud.githubusercontent.com/assets/7429672/6002410/57bb4320-aaf3-11e4-82e8-20c8049baaca.png)

**Comment by jziaja** [comment] 2015-02-02 16:30
Thanks for reporting this @antonio-bakula !  I'll include this fix in the next release.  I'm also going to forward this error to the payments team as it should be returning a 'missing data' data with a description of the missing field.

**Comment by jziaja** [comment] 2015-02-02 18:33
@antonio-bakula, do you mind sharing what the payment request looks like with the missing state information?  I'm trying to reproduce this, but I'm not seeing same UNKNOWN_ERROR response.  Thanks!

**Comment by jziaja** [comment] 2015-02-02 19:36
This actually looks to already be fixed in the current version of the SDK.  I originally thought your code snapshot was from the current repo, but it looks like that's from an older version of the PaymentsException class.  [It has since been updated to handle a missing details property](https://github.com/paypal/PayPal-NET-SDK/blob/master/Source/SDK/Exception/PaymentsException.cs#L31).  If you update to the [current version](https://www.nuget.org/packages/PayPal) of the library (looking at the logs for that `debug_id`, it appears you're using version 0.11.0 of the older RestApiSdk library), then that should resolve the issue.

Regardless, I'd still like to notify the payments team of the UNKNOWN_ERROR being returned as there's a use-case the API isn't handling properly.

**Closed by jziaja** 2015-02-02 19:36 UTC

**Comment by antonio-bakula** [comment] 2015-02-02 19:39
Oh, sorry.

Here is the json request that causes that UNKNOWN_ERROR:

{
  "intent":"sale",
  "payer":{
    "payment_method":"paypal",
    "payer_info":{
      "first_name":"Antonio",
      "last_name":"Bakula"
    }
  },
  "transactions":[
    {
      "amount":{
        "currency":"EUR",
        "total":"5.00",
        "details":{
          "shipping":"0.00",
          "subtotal":"5.00",
          "tax":"0.00"
        }
      },
      "description":"Unit test payment - ebfa7659-d651-41f4-9f1c-7f85ab8c84bc",
      "invoice_number":"ebfa7659-d651-41f4-9f1c-7f85ab8c84bc",
      "item_list":{
        "items":[
          {
            "quantity":"2",
            "name":"Test Product",
            "price":"2.50",
            "currency":"EUR",
            "sku":"PC0001"
          }
        ],
        "shipping_address":{
          "recipient_name":"Antonio Bakula",
          "line1":"1435 Prince of Wales Drive #601",
          "line2":"",
          "city":"Ottawa",
          "country_code":"CA",
          "postal_code":"ON K2C 1N5",
          "phone":"1 613-402-1203"
        }
      }
    }
  ],
  "redirect_urls":{
    "return_url":"http://localhost/paypalpayment?ok=1&cart=ebfa7659-d651-41f4-9f1c-7f85ab8c84bc",
    "cancel_url":"http://localhost/paypalpayment?ok=0&cart=ebfa7659-d651-41f4-9f1c-7f85ab8c84bc"
  }
}

**Comment by jziaja** [comment] 2015-02-02 19:41
Thanks! :)
