### ISSUE TITLE
Question about SDK exception design strategy

### ISSUE THREAD

**Issue by AdamRiddick** [paypal/PayPal-NET-SDK#75] opened 2015-02-03 07:47 UTC
For the following payment request, I am receiving an empty Payment Exception;

````json
{
	"intent": "sale",
	"payer": {
		"payment_method": "paypal"
	},
	"transactions": [{
		"amount": {
			"currency": "GBP",
			"total": "11.82",
			"details": {
				"subtotal": "4.02",
				"shipping": "7.00",
				"tax": "0.80"
			}
		},
		"description": "Order Number: 5",
		"invoice_number": "502/02/2015 16:39:07",
		"item_list": {
			"items": [{
				"quantity": "1.00",
				"name": "Rubber Chicken",
				"price": "5.90",
				"currency": "GBP",
				"sku": "P-TOY-RUBBERCHICKEN"
			},
			{
				"quantity": "1",
				"name": "Subtotal Discount",
				"price": "-0.59",
				"currency": "GBP",
				"sku": "discount_sku"
			},
			{
				"quantity": "1",
				"name": "Subtotal Inc. Shipping Discount",
				"price": "-1.29",
				"currency": "GBP",
				"sku": "discount_sku"
			}]
		}
	}],
	"redirect_urls": {
		"return_url": "http://localhost:44300//PayPal/CompletedPayment?orderEntityKey=5",
		"cancel_url": "http://localhost:44300//Order/FinaliseOrder?orderEntityKey=5"
	}
}
````

**Comment by AdamRiddick** [comment] 2015-02-03 08:05
Ok, this isn't actually an Issue, but has turned into a question.

The PaymentsException is a child of HttpException, and somewhere up the chain they inherit from Exception.

Why does the PaymentException define it's own details page, and not utilise the mechanisms provided by .Net in the reporting of error messages? Through use of the Data, Message and InnerException fields, as intended?

**Comment by jziaja** [comment] 2015-02-03 17:20
Great question @AdamRiddick! :+1:   The state of the current exception handling is designed the way it is as a direct result from working with developers in the past here on GitHub.  As is the case with any open source project, if you have thoughts on a different way to approach dealing with exceptions, you're more than welcome to submit a pull request to this repo that includes your changes and additions.  Be aware, however, that architectural changes to the exception handling may require a major rev to the project if the changes are significant and breaking.

With that said, here's a bit of background on the state of the exception classes.

As you pointed out, the hierarchy for the `PaymentsException` class is the following:
* [`PaymentsException`](https://github.com/paypal/PayPal-NET-SDK/blob/master/Source/SDK/Exception/PaymentsException.cs)
  * [`HttpException`](https://github.com/paypal/PayPal-NET-SDK/blob/master/Source/SDK/Exception/HttpException.cs)
    * [`ConnectionException`](https://github.com/paypal/PayPal-NET-SDK/blob/master/Source/SDK/Exception/ConnectionException.cs)
      * [`PayPalException`](https://github.com/paypal/PayPal-NET-SDK/blob/master/Source/SDK/Exception/PayPalException.cs)
        * `System.Exception`

The reason for this design approach is it allows exceptions thrown from the SDK to contain all the pertinent data **upfront for the developer to reference** (i.e. all the properties with the PayPal-specific details of the exception are available immediately in the caught exception object).  This was an intentional design decision and avoids requiring developers to 'walk' the `InnerException` tree hunting for the details they might be interested in (which is how it was designed in the past where everything exception caught was added to the `InnerException` tree and resulted in developers getting confused on where the error info was located, or frustration on having to delve so deeply into the list of exceptions).  This is more of a C# design philosophy that some either agree or disagree with, but the end goal for the exception caught by a developer was to give them everything they might be interested in right there in the exception's top-level properties.

The hierarchy also has the added benefit of allowing developers to construct their `try-catch` statements to simply catch exceptions of type `PayPalException` and then interrogate the object to see if it's another type.  One could argue that this is where we could use the `InnerException` to provide the more in-depth exception object with all the pertinent properties (e.g. a `PaymentsException` could be set as the `InnerException` of a `PayPalException`), and this is where I'd be open for a pull request to discuss further. :)

Regarding the `Message` property, this is set on some exceptions, but not all exceptions that are thrown.  If it would help to provide more message details that accompany the thrown exception, please feel free to propose those messages, or let us know where there might be a gap we should fill.

As for the `Data` property of the `System.Exception` class, I'm honestly not a fan of using this property.  The `Data` property represents an arbitrary collection of data that the user has to hunt around in or know how to access ahead of time to get the exception details they need.  The current design approach allows us to provide known properties on the exception objects that a developer can easily code against with Intellisense guiding them on what information is available.  Designed correctly, this has the added benefit of the SDK self-documenting in the code as to what's available for developers to catch, reducing the need for the developer to reference SDK-specific documentation on how to find certain exception details in certain cases.  Again, the design isn't perfect, so if there's a counterpoint to this approach where `Data` would provide a better developer experience, I'd love to hear it. :)

Hopefully that answers your questions, and let me know if there's anything you need further clarification on.  I'll leave this issue open for a while as I'd love to hear more thoughts from you and other developers about exception-class design strategies and approaches.

**Comment by jziaja** [comment] 2015-02-03 18:34
Just so others are aware, the caught `PaymentsException` object in the above case will cause an exception to be thrown in the code that looks like the following when using the VS debugger:

![image](https://cloud.githubusercontent.com/assets/8227966/6026484/1f494a26-ab90-11e4-8be2-1a3a428a5639.png)


This is where I definitely agree that an improvement should be made with setting the `Message` property on the exception, and reinforces your initial finding of the blank error message. :)

**Comment by AdamRiddick** [comment] 2015-02-04 11:44
Thanks for getting back to me with an explanation @jziaja.

I will look into spending some time through a pull request. None of the changes would be architectural, but to provide more visibility to the existing exception structure.

The `Details` property does provide a large range of useful information. Knowing it existed allowed me to solve my problems very quickly, however I feel the visibility of the error messages can be poor, consider the following;

    Exception ex = ((HttpApplication)sender).Context.Server.GetLastError();

Should the above line of code be used within an `Application_Error`, found in the `global.asax` file, it has the ability of being agnostic of individual exception types. Error reporting can then handle all exceptions that can be thrown by a system or third party provider, and provide a wealth of information for a developer after the event has occurred.

I agree with the use of the exceptions as only specific types should ever be caught, however, as with the above example; the `Details` property would be hiding information away from the intended use of exceptions. `InnerException` can be a nuisance to traverse, though the purpose of the `Data` dictionary within `System.Exception` is to provide additional user-defined information about the exception [As Per: https://msdn.microsoft.com/en-us/library/system.exception.data.aspx]. 

I believe the ability to derive from `System.Exception` is not to alter the structure to hold additional information, but to allow for client code to catch only the exceptions for which it is equipped to handle. The `Data` property could handle the data contained within the `Details` property, with a different structure. As you stated that the user must be aware of the `Data` keys ahead of time, though knowledge `Details` property would also be required, as well as knowing the type of the `System.Exception` derivative. A lot of current systems will be aware of the Exception structure as blueprinted within System.Exception, and will expect the structure of derivatives to provide information using the same mechanisms.

The addition I would suggest would take that data and traverse it into the original `System.Exception` structure. This would mean the data is duplicated, but covers each eventuality in the handling of the exception.

It may be that there is something I haven't considered and I'm completely off the mark, so thank you for keeping this discussion open.

**Comment by jziaja** [comment] 2015-02-04 17:10
Great points, @AdamRiddick!  The current exception format is designed entirely around the notion of an object being caught somewhere, not via an error event like `Application_Error` where the exception object must be requested.  With that in mind, I definitely agree that populating the available `System.Exception` properties would give developers more flexibility in terms of handling the exception.

To your point of duplicating the data, I think expanding the visibility of the error details in the object is much better than limiting it to only being used one way.  As long as the data is duplicated in a consistent manner when the SDK raises the exception, then it should be fine.

Looking forward to seeing the pull request!

**Comment by jziaja** [comment] 2015-02-19 16:22
@AdamRiddick, would you mind taking a look at the [improve-exceptions](https://github.com/paypal/PayPal-NET-SDK/tree/improve-exceptions) branch I just created?  Both the [`PaymentsException`](https://github.com/paypal/PayPal-NET-SDK/blob/improve-exceptions/Source/SDK/Exception/PaymentsException.cs#L25) and [`IdentityException`](https://github.com/paypal/PayPal-NET-SDK/blob/improve-exceptions/Source/SDK/Exception/IdentityException.cs#L29) classes set the `HelpLink` and `Data` properties.

**Comment by CodingSamurai** [comment] 2015-06-18 06:05
I have to admit that this issue threw me when I was initially developing against the newer API.  The top level exception being blank made me think that somehow the API was broken because of credentials or something else, not that there was an underlying error.  

So at the very least it would be nice to have a top level error message and then dive into the details object for the nitty gritty of what went wrong.

**Comment by jziaja** [comment] 2015-06-18 13:22
@CodingSamurai, the issue about the top-level exception being blank should have been resolved in version 1.4 of this SDK.  Are you saying it's still blank?  If so, can you share the situation in which you caught the exception with a blank message? Thanks!

**Comment by CodingSamurai** [comment] 2015-06-18 13:33
Yes it was still blank for me. I updated the package with NuGet and was doing a sale payment with order items. I was specifically seeing it with the following two errors: 

1.) Missing recipient name in shipping address 
2.) Incorrect CVV length 


----- Original Message -----

**Comment by jziaja** [comment] 2015-06-18 14:10
I just tested this using the sample project and the latest version 1.5 of this SDK.  Here are the exceptions caught for each of the cases you mentioned:

_Missing recipient name in shipping address_
![image](https://cloud.githubusercontent.com/assets/8227966/8233010/64b0b82e-1599-11e5-88c5-d9072b3945e6.png)

_Incorrect CVV length exception_
![image](https://cloud.githubusercontent.com/assets/8227966/8233043/a08834e4-1599-11e5-8b6a-8c4f5d3dfc85.png)

Are you seeing something different?

**Comment by jziaja** [comment] 2015-11-11 14:29
Closing this due to inactivity.  Feel free to chime in if you have other thoughts on a better exception strategy.  As always, feel free to [submit a PR](https://github.com/paypal/PayPal-NET-SDK/pulls) with any suggestions.  Thanks!

**Closed by jziaja** 2015-11-11 14:29 UTC
Labels: question, sdk-enhancement
