### ISSUE TITLE
The remote server returned an error: (500) Internal Server Error.

### ISSUE THREAD

**Issue by ctallos** [paypal/PayPal-NET-SDK#344] opened 2018-03-05 17:12 UTC
Could anyone help with this? Using the most recent version of PayPal sdk
{paypal-debug-id: 82e9a35334a3d,82e9a35334a3d
Content-Language: *
X-SLR-RETRY: 500
X-SLR-RETRY-API: /v1/payments/payment
Connection: close
HTTP_X_PP_AZ_LOCATOR: sandbox.slc
Date: Sun, 04 Mar 2018 06:19:21 GMT
Set-Cookie: X-PP-SILOVER=name%3DSANDBOX3.API.1%26silo_version%3D1880%26app%3Dapiplatformproxyserv%26TIME%3D3918502746%26HTTP_X_PP_AZ_LOCATOR%3Dsandbox.slc; Expires=Sun, 04 Mar 2018 06:49:51 GMT; domain=.paypal.com; path=/; Secure; HttpOnly,X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT
Server: Apache
Vary: Authorization
Content-Length: 184
Content-Type: application/json}
{"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error occurred.","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"82e9a35334a3d"}

General information
Chrome 63, Windows 10,

Issue description
Occurs at this line
try
{
APIContext apiContext = Extensions.Configuration.GetApiContext();
Payment createdPayment = pymnt.Create(apiContext); <-----------------

**Comment by xiaoleih41** [comment] 2018-03-06 18:44
Are you trying to do a credit card transaction using REST SDK? This might have been caused by an over used sandbox credit card number. You can generate a new credit card number to try again. However, as PayPal has stopped onboarding direct credit card integration through REST API, if you haven't got the live credential approved, please consider to integration Braintree SDK instead as it supports both PayPal and credit card payment method.

**Comment by xiaoleih41** [comment] 2018-03-12 14:43
Close the issue as the solution has been given.

**Closed by xiaoleih41** 2018-03-12 14:43 UTC

**Comment by NoAvailableAlias** [comment] 2018-04-18 16:00
We're currently getting this very same issue now, however, we're using an account that has had its "live" credentials approved. Is this still expected for such an account in "sandbox" mode?

Edit: It seems like using a lesser used test card number might alleviate this issue. That and retrying the operation.

**Comment by xiaoleih41** [comment] 2018-04-18 16:10
If you are using a live credential with direct credit card feature approved, you should not experience it in live environment as it's an sandbox specific issue for any over used sandbox credit card number. You can try to create a new number by using any online card generator.
