### ISSUE TITLE
When processing a payment, can I get back the Transaction ID, etc?

### ISSUE THREAD

**Issue by MLyons10** [paypal/PayPal-NET-SDK#70] opened 2015-01-26 23:53 UTC
I can't seem to find a way to do this anywhere, is anyone able to tell me how I might do this?  I would like to log this for my records.

**Comment by jziaja** [comment] 2015-01-27 05:57
Hi @MLyons10, the transaction ID can be found via the [`related_resources`](https://github.com/paypal/PayPal-NET-SDK/blob/master/Source/SDK/Api/RelatedResources.cs) property of each `transaction` associated with a payment.

Here's a code sample of how to get the transaction ID for a sale payment, along with how it looks using the sample project:

````csharp
var payment = Payment.Get(apiContext, "PAY-89W644977H834061FKTDRCCY");
var transactionId = payment.transactions[0].related_resources[0].sale.id;
````

![image](https://cloud.githubusercontent.com/assets/8227966/5914097/b3310454-a5b4-11e4-8a1e-401e3f1aac78.png)

**Comment by MLyons10** [comment] 2015-01-29 02:50
Thank you very much for your help.  That works perfectly.  

Am I able to get detailed information when an error is returned?  I see that I get a 400 Error, but I was hoping to be able to get some detail as to what actually is the issue...  I can't for the life of me figure out what is causing it to return an error...

Thanks for your help.

**Comment by jziaja** [comment] 2015-01-29 03:30
Yes, depending on where the 400 Error is encountered, a [`PaymentsException`](https://github.com/paypal/PayPal-NET-SDK/blob/master/Source/SDK/Exception/PaymentsException.cs) may be thrown and includes a [`Details`](https://github.com/paypal/PayPal-NET-SDK/blob/master/Source/SDK/Exception/PaymentsException.cs#L12) property that provides quick access to the cause of the error.  Otherwise, an [`HttpException`](https://github.com/paypal/PayPal-NET-SDK/blob/master/Source/SDK/Exception/HttpException.cs) will be thrown (which `PaymentsException` inherits off of), and includes a [`Response`](https://github.com/paypal/PayPal-NET-SDK/blob/master/Source/SDK/Exception/ConnectionException.cs#L10) property that contains the response from the server.

An easy way to test this in the samples is to inject bogus data into an object and view the details of the exception that is thrown.  In the run below, I changed the sample for making a PayPal payment so the `transactions[0].amount.details.tax` value was set to the letter 'a', thus resulting in a 400 error response and a `PaymentsException` being thrown by the SDK:
![image](https://cloud.githubusercontent.com/assets/8227966/5951981/9c426400-a734-11e4-91b4-5ca04883d883.png)

**Comment by jziaja** [comment] 2015-01-29 03:41
I should also mention that if you do get an error that you're having trouble understanding (some of the errors can be quite cryptic), sharing the `debug_id` contained in the error response with us here will allow our team to look up the specific details of what caused the error.

**Comment by jziaja** [comment] 2015-02-05 15:08
Closing this issue as the questions have been answered.  Let me know if there's anything else you need help with. :)

**Closed by jziaja** 2015-02-05 15:08 UTC
Labels: question
