### ISSUE TITLE
Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by MegaSoftwares** [paypal/PayPal-NET-SDK#139] opened 2016-01-24 15:00 UTC
I have downloaded https://github.com/paypal/PayPal-NET-SDK and running sample, till yesterday it was working like charm but today I am getting error  "Invalid HTTP response: The request was aborted: Could not create SSL/TLS secure channel." . Any clue why it suddenly started giving error?

**Comment by johnje** [comment] 2016-01-24 20:19
I'm having fits over the same thing, trying (for the first time) to use NVP. I haven't walked all the way through it, but found this: https://www.paypal-knowledge.com/infocenter/index?page=content&id=FAQ1914&expand=true&locale=en_US

**Comment by marekwee** [comment] 2016-01-25 11:35
Same issue...does anybody knows what's wrong?

**Comment by meetonvc-chris** [comment] 2016-01-25 14:06
It's because of the move to TLS 1.2 and the shutting off of SSL 3.0. More information can be found [here](https://www.paypal.com/uk/webapps/mpp/ssl-security-update):

I got it working by adding the following to the constructor on the Configuration class:

    			System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls12;

**Comment by marekwee** [comment] 2016-01-25 14:11
Great! That solves my problem. Thanks.

**Comment by pp-randy** [comment] 2016-01-25 14:15
@MegaSoftwares the issue is most likely related to the TLS 1.2 change mentioned above. Closing the issue for now, but reply back if you are unable to resolve.

**Closed by pp-randy** 2016-01-25 14:15 UTC
Labels: question

**Comment by HoneyShyam** [comment] 2017-08-20 17:31
I am facing the same issue when trying to validate a Pay request using REST request.
Anyone have the working example, I have tried to add System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls12; but not able to get OK status and response and error is still exists.

Thank you 
Shyam

**Comment by pp-randy** [comment] 2017-08-21 22:32
@HoneyShyam you are getting this exact error?  Please make sure you meet the .Net requirements found here https://github.com/paypal/tls-update.
